BEGIN;

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_salt BYTEA NOT NULL,
    password_hash BYTEA NOT NULL,
    app_data JSONB NOT NULL DEFAULT '{"players":[],"history":[],"preferredSize":4}'::jsonb,
    profile_data JSONB NOT NULL DEFAULT '{"discordName":"","activisionId":"","email":"","avatar":""}'::jsonb,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    approved BOOLEAN NOT NULL DEFAULT TRUE,
    created_at BIGINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS accounts_username_ci ON accounts (lower(username));

CREATE TABLE IF NOT EXISTS sessions (
    token_hash TEXT PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    token_hash TEXT PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS password_reset_tokens_expiry ON password_reset_tokens (expires_at);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_presence (
    token_hash TEXT PRIMARY KEY REFERENCES sessions(token_hash) ON DELETE CASCADE,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    last_seen BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS chat_presence_account ON chat_presence (account_id, last_seen);

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS rotation_experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    rotation_id TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    UNIQUE (account_id, rotation_id)
);

CREATE TABLE IF NOT EXISTS direct_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS direct_messages_sender_recipient ON direct_messages (sender_id, recipient_id, id);
CREATE INDEX IF NOT EXISTS direct_messages_recipient_sender ON direct_messages (recipient_id, sender_id, id);

CREATE TABLE IF NOT EXISTS friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_low BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    user_high BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'accepted')),
    created_at BIGINT NOT NULL,
    CHECK (user_low < user_high),
    CHECK (requester_id = user_low OR requester_id = user_high),
    UNIQUE (user_low, user_high)
);
CREATE INDEX IF NOT EXISTS friendships_user_low ON friendships (user_low, status);
CREATE INDEX IF NOT EXISTS friendships_user_high ON friendships (user_high, status);

ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_presence ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE rotation_experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE direct_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE friendships ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE accounts, sessions, password_reset_tokens, app_settings,
    chat_presence, chat_messages, rotation_experience, direct_messages, friendships
    FROM anon, authenticated;
REVOKE ALL ON SEQUENCE accounts_id_seq, chat_messages_id_seq,
    rotation_experience_id_seq, direct_messages_id_seq, friendships_id_seq
    FROM anon, authenticated;

COMMIT;
